# Generated by Django 4.2.7 on 2023-11-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_replycomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replycomment',
            old_name='created_on',
            new_name='replied_created_on',
        ),
        migrations.RenameField(
            model_name='replycomment',
            old_name='name',
            new_name='replier_name',
        ),
        migrations.RenameField(
            model_name='replycomment',
            old_name='body',
            new_name='reply_body',
        ),
        migrations.RenameField(
            model_name='replycomment',
            old_name='comment',
            new_name='reply_comment',
        ),
    ]
