# Generated by Django 4.2.7 on 2023-11-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_created_on_replycomment_replied_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replycomment',
            old_name='replied_created_on',
            new_name='reply_created_on',
        ),
        migrations.RenameField(
            model_name='replycomment',
            old_name='replier_name',
            new_name='reply_name',
        ),
    ]
