# Generated by Django 4.2.7 on 2023-11-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_replied_created_on_replycomment_reply_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replycomment',
            old_name='reply_comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='replycomment',
            old_name='reply_body',
            new_name='reply',
        ),
        migrations.RenameField(
            model_name='replycomment',
            old_name='reply_created_on',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='replycomment',
            old_name='reply_name',
            new_name='user',
        ),
    ]
