# Generated by Django 4.2.7 on 2023-11-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_replycomment_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
